# Generated by Django 4.1.5 on 2023-01-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('entry', models.CharField(max_length=10000)),
                ('report_day', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
