# Generated by Django 4.1.5 on 2023-01-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habitjournal_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitjournal',
            name='report_day',
            field=models.DateTimeField(max_length=10000),
        ),
    ]
